# Generated by Django 3.0.7 on 2020-08-03 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameBase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('current_points', models.IntegerField(default=0)),
                ('cashed_in_amount', models.IntegerField(default=0)),
                ('done_by', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='accounts.Profile')),
            ],
        ),
    ]
