# Generated by Django 3.0.7 on 2020-08-03 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamebase',
            name='done_by',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='game_base', to='accounts.Profile'),
        ),
    ]
