# Generated by Django 3.0.7 on 2020-08-05 16:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_auto_20200805_1732'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamebase',
            name='xp',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10000000)]),
        ),
    ]
