# Generated by Django 3.0.7 on 2020-08-05 17:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_enemy'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enemy',
            old_name='hp',
            new_name='current_hp',
        ),
        migrations.AddField(
            model_name='enemy',
            name='max_hp',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10000000)]),
        ),
    ]
