# Generated by Django 3.0.7 on 2020-08-06 16:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_auto_20200805_1800'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamebase',
            name='kills',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10000000)]),
        ),
    ]
