# Generated by Django 3.0.7 on 2020-06-23 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Squat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=0)),
                ('done_on', models.DateTimeField(auto_now_add=True)),
                ('done_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='squats', to='accounts.Profile')),
            ],
        ),
    ]
