# Generated by Django 3.0.7 on 2020-06-24 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0002_exercise_workout'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Squat',
        ),
    ]
